### ISSUE TITLE
Default Fanart and Default Paint for Systems?

### ISSUE THREAD

**Issue by NewYears1978** [lehcimcramtrebor/es-theme-RCBX#1]
Is it possible to set a DefaultFanart and DefaultPaint for system specific?

Some systems don't have good Fanart so it would be nice to have a default system background for those systems on the menu and within the gamelist.

Probably possible but I am new and not sure how to set it.

**Comment by lehcimcramtrebor** [comment]
Here you can watch how to customize backgrounds for a specific system: https://www.youtube.com/watch?v=2J6M5ZR7ybU&t=37s , other videos on my channel can help you but all customs are explained in diferrent readme files in _rcbxCustom folder.

**Comment by NewYears1978** [comment]
I figured it out, thanks for your help and for the incredible theme :) Also sorry for all my message on YT and here :) Can't learn if you don't ask questions hehe.
