### ISSUE TITLE
Fonts too small

### ISSUE THREAD

**Issue by SpectralVoid31** [lehcimcramtrebor/es-theme-RCBX#5]
I use your theme on the M17 Handheld, and the letters in the platform descriptions appear very small, and I wanted to know if there is any file I can edit to change this

**Comment by lehcimcramtrebor** [comment]
It is not planned to have descriptions with a small screen. It seems you use bad mode, there are two options when a resolution lower than 640x480 is detected: crt mode and handheld mode.. with a portable console it is planned to use handheld mode. The option is found in the theme configuration menu.

**Comment by SpectralVoid31** [comment]
> It is not planned to have descriptions with a small screen. It seems you use bad mode, there are two options when a resolution lower than 640x480 is detected: crt mode and handheld mode.. with a portable console it is planned to use handheld mode. The option is found in the theme configuration menu.

Do you know which file I should change, which variable? because the emuelec of this device is very limited

**Comment by SpectralVoid31** [comment]
My friend solved the problem
